#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gomicro/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

include Hooky::Redis

# Setup
config = converge( Hooky::Redis::CONFIG_DEFAULTS, payload[:config] || {} )

# set redis config
ip         = `ifconfig eth0 | awk '/inet addr/ {print $2}' | cut -f2 -d':'`.to_s.strip
main_ip    = payload[:members].select { |mem| mem[:role] == 'primary'}[0][:local_ip]
main       = (main_ip == ip) ? false : main_ip
sentinel   = (payload[:members].select { |mem| mem[:role] == 'arbitrator'}[0][:local_ip] == ip) ? main_ip : '127.0.0.1'
total_mem  = `vmstat -s | grep 'total memory' | awk '{print $1}'`.to_i
cgroup_mem = `cat /sys/fs/cgroup/memory/memory.limit_in_bytes`.to_i
maxmemory  = [ total_mem / 1024, cgroup_mem / 1024 / 1024 ].min

directory '/data/etc/redis' do
  owner 'gomicro'
  group 'gomicro'
end

directory '/data/etc/flip' do
  owner 'gomicro'
  group 'gomicro'
end

if ['default', 'primary', 'secondary'].include? payload[:member][:role]
  # configure redis for redundancy
  template '/data/etc/redis/redis.conf' do
    source 'redis-redundant.conf.erb'
    mode 0644
    variables ({ config: config , slaveof: main, maxmemory: maxmemory})
    owner 'gomicro'
    group 'gomicro'
  end

  # configure sentinel to provide redundancy
  template '/data/etc/redis/sentinel.conf' do
    source 'sentinel.conf.erb'
    mode 0644
    variables ({ main: main_ip })
    owner 'gomicro'
    group 'gomicro'
  end

  # configure redis-proxy to provide high availability and interaction with sentinel
  template '/data/etc/redis/redis-proxy.conf' do
    source 'redis-proxy.conf.erb'
    mode 0644
    variables ({ sentinel_ip: sentinel })
    owner 'gomicro'
    group 'gomicro'
  end

  # set flip.conf
  template '/data/etc/flip/flip.conf' do
    mode 0644
    variables ({
      payload: payload
    })
  end
elsif payload[:member][:role] == 'arbitrator'
  template '/data/etc/redis/sentinel.conf' do
    source 'sentinel.conf.erb'
    mode 0644
    variables ({ main: main_ip })
    owner 'gomicro'
    group 'gomicro'
  end

  # set flip.conf
  template '/data/etc/flip/flip.conf' do
    mode 0644
    variables ({
      payload: payload
    })
  end

  if payload[:logvac_host]
    # Narc Setup
    template '/opt/gomicro/etc/narc.conf' do
      source 'narc.conf.erb'
      variables ({
        logvac: payload[:logvac_host],
        uid: payload[:component][:uid]
      })
    end

    directory '/etc/service/narc'

    template '/etc/service/narc/run' do
      mode 0755
      source 'run-root.erb'
      variables ({ exec: "/opt/gomicro/bin/narcd /opt/gomicro/etc/narc.conf" })
    end
  end
end
