#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gomicro/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

service "flip" do
  action :disable
  init :runit
  not_if { !Dir.exist?('/etc/service/flip') }
end

service "sentinel" do
  action :disable
  init :runit
  not_if { !Dir.exist?('/etc/service/sentinel') }
end

file '/etc/microinit.d/mroute' do
  action :delete
  not_if { !File.exist?('/etc/microinit.d/mroute') }
end

directory '/etc/service/flip' do
  action :delete
  not_if { !Dir.exist?('/etc/service/flip') }
end

directory '/etc/service/sentinel' do
  action :delete
  not_if { !Dir.exist?('/etc/service/sentinel') }
end
